{% set name = "PySolid" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/insarlab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6f46e77b3db7d2e186cb74d8f51ed92d35ab1ee0a2ab5f793d46ec7b9e3f5176

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}

  host:
    - m2w64-toolchain  # [win]
    - libpython  # [win]
    - python
    - pip
    - numpy
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - scikit-image

test:
  imports:
    - pysolid

about:
  home: https://github.com/insarlab/PySolid
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python wrapper for solid to compute solid Earth tides
  description: |
    The Python based solid Earth tides (PySolid) is a thin Python wrapper of the
    solid.for program (by Dennis Milbert based on `dehanttideinelMJD.f` from
    V. Dehant, S. Mathews, J. Gipson and C. Bruyninx) to calculate solid Earth
    tides in east/north/up direction (section 7.1.1 in the 2010 IERS Conventions).
    Solid Earth tides introduces very long spatial wavelength range components in
    SAR/InSAR observations, as shown in the Sentinel-1 data with regular
    acquisitions and large swaths (Fattahi et al., 2020).
  dev_url: https://github.com/insarlab/PySolid

extra:
  recipe-maintainers:
    - jhkennedy
    - jlrine2
    - yunjunz
