{% set name = "PySolid" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jhkennedy/{{ name }}/archive/refs/heads/pipify.tar.gz
  sha256: 519e73242e4001daa1519c3bded2980f75bb9ba09c6bd7d9c9121f023f580e3c
  # url: https://github.com/insarlab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: bfb503cebe9f5bca2c2d4cb8c223e2348d9118d76f8f5c07573239ff559acd14

build:
  number: 0
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_fortran') }}  # [win]

  host:
    - m2w64-toolchain  # [win]
    - libpython  # [win]
    - python
    - pip
    - numpy
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - scikit-image

test:
  imports:
    - pysolid

about:
  home: https://github.com/insarlab/PySolid
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python wrapper for solid to compute solid Earth tides'
  description: |
    The Python based solid Earth tides (PySolid) is a thin Python wrapper of the
    solid.for program (by Dennis Milbert based on `dehanttideinelMJD.f` from
    V. Dehant, S. Mathews, J. Gipson and C. Bruyninx) to calculate solid Earth
    tides in east/north/up direction (section 7.1.1 in the 2010 IERS Conventions).
    Solid Earth tides introduces very long spatial wavelength range components in
    SAR/InSAR observations, as shown in the Sentinel-1 data with regular
    acquisitions and large swaths (Fattahi et al., 2020).
  dev_url: https://github.com/insarlab/PySolid

extra:
  recipe-maintainers:
    - jhkennedy
    - jlrine2
    - yunjunz
