{% set name = "pysolid" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f28f5b50105d259bc55695af207cc8f730f4b5f1ac4fb6f9e15a57f8688113e
  patches:
    - windows-path-patch.diff  # See https://github.com/conda-forge/pysolid-feedstock/issues/20

build:
  number: 4
  skip: true  # [py<36]
  script_env:
    - SKBUILD_CMAKE_ARGS="-GNinja"
    - FC=gfortran  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - ninja
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}

  host:
    - libpython  # [win]
    - python
    - pip
    - scikit-build-core
    - numpy
    - setuptools
    - setuptools_scm
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - pysolid

about:
  home: https://github.com/insarlab/PySolid
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python wrapper for solid to compute solid Earth tides
  description: |
    The Python-based solid Earth tides (PySolid) is a thin Python wrapper of the
    `solid.for` program (by Dennis Milbert based on `dehanttideinelMJD.f` from
    V. Dehant, S. Mathews, J. Gipson and C. Bruyninx) to calculate solid Earth
    tides in the east/north/up direction (section 7.1.1 in the 2010 IERS Conventions).
    Solid Earth tides introduce large offsets in SAR observations and long spatial
    wavelength ramps in InSAR observations, as shown in the Sentinel-1 data with
    regular acquisitions and large swaths (Yunjun et al., 2022).
  dev_url: https://github.com/insarlab/PySolid

extra:
  recipe-maintainers:
    - jhkennedy
    - jlrine2
    - scottstanie
    - yunjunz
